"""empty message

Revision ID: 967cbacdaaa8
Revises: 
Create Date: 2021-03-13 23:10:03.357927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967cbacdaaa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'region', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region', type_='unique')
    op.alter_column('region', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
